version: '3'

services:
  postgres:
    image: 'postgres:13'
    container_name: 'test-database'
    ports:
      - "5429:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=test'
      - 'POSTGRES_PASSWORD=postgres'